#!/usr/bin/env bash
set -euo pipefail

PROFILE="${HOS_AWS_PROFILE:-HopeOneSource-Dev}"
COMPAT_PROFILE="${HOS_COMPAT_AWS_PROFILE:-HOP42-Sandbox-Developer}"
REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-us-east-1}}"
ENV_FILE="${HOS_ENV_FILE:-.env.local}"
SECRET_DIR="${HOS_SECRET_DIR:-.secrets}"

printf 'HopeOneSource team dev secrets loader\n'
printf 'Blast radius: Level 1 read-only secret retrieval. This script writes local ignored files and does not write external data.\n\n'

if ! command -v aws >/dev/null 2>&1; then
  printf 'FAIL: aws cli is not installed\n' >&2
  exit 1
fi

profiles="$(aws configure list-profiles 2>/dev/null || true)"
if printf '%s\n' "$profiles" | grep -qx "$PROFILE"; then
  :
elif printf '%s\n' "$profiles" | grep -qx "$COMPAT_PROFILE"; then
  printf 'WARN: AWS profile %s missing; using compatibility profile %s\n' "$PROFILE" "$COMPAT_PROFILE"
  PROFILE="$COMPAT_PROFILE"
else
  printf 'FAIL: AWS profile %s missing\n' "$PROFILE" >&2
  exit 1
fi

mkdir -p "$SECRET_DIR"
chmod 700 "$SECRET_DIR"

fetch_secret() {
  local primary="$1"
  local fallback="$2"
  local value

  if value="$(AWS_REGION="$REGION" aws secretsmanager get-secret-value --profile "$PROFILE" --secret-id "$primary" --query SecretString --output text 2>/dev/null)"; then
    printf '%s' "$value"
    return 0
  fi

  if value="$(AWS_REGION="$REGION" aws secretsmanager get-secret-value --profile "$PROFILE" --secret-id "$fallback" --query SecretString --output text 2>/dev/null)"; then
    printf 'WARN: using compatibility secret %s\n' "$fallback" >&2
    printf '%s' "$value"
    return 0
  fi

  printf 'FAIL: unable to read %s or %s\n' "$primary" "$fallback" >&2
  return 1
}

sf_json="$(fetch_secret 'hope1source/dev/salesforce/jwt' 'hope1source/hop43/salesforce-jwt')"
google_json="$(fetch_secret 'hope1source/dev/google/service-account' 'hope1source/hop43/google-service-account')"

tmp_env="$(mktemp)"
tmp_sf="$(mktemp)"
tmp_google="$(mktemp)"
trap 'rm -f "$tmp_env" "$tmp_sf" "$tmp_google"' EXIT

printf '%s' "$sf_json" > "$tmp_sf"
printf '%s' "$google_json" > "$tmp_google"

SF_PRIVATE_KEY_PATH="$SECRET_DIR/salesforce-jwt-private-key.pem"
GOOGLE_SERVICE_ACCOUNT_PATH="$SECRET_DIR/google-service-account.json"
GOOGLE_PRIVATE_KEY_PATH="$SECRET_DIR/google-service-account-private-key.pem"

node scripts/write-team-dev-env.mjs \
  "$tmp_sf" \
  "$tmp_google" \
  "$tmp_env" \
  "$SF_PRIVATE_KEY_PATH" \
  "$GOOGLE_SERVICE_ACCOUNT_PATH" \
  "$GOOGLE_PRIVATE_KEY_PATH"

cat > "$ENV_FILE" <<EOF_ENV
# Generated by npm run dev:secrets.
# Local development only. Do not commit or paste these values.
AWS_PROFILE=$PROFILE
AWS_REGION=$REGION
$(cat "$tmp_env")
EOF_ENV

chmod 600 "$ENV_FILE" "$SF_PRIVATE_KEY_PATH" "$GOOGLE_SERVICE_ACCOUNT_PATH" "$GOOGLE_PRIVATE_KEY_PATH"

printf 'OK: wrote %s\n' "$ENV_FILE"
printf 'OK: wrote %s\n' "$SF_PRIVATE_KEY_PATH"
printf 'OK: wrote %s\n' "$GOOGLE_SERVICE_ACCOUNT_PATH"
printf 'OK: wrote %s\n' "$GOOGLE_PRIVATE_KEY_PATH"
printf 'Next: source %s or use a dotenv-aware local runner.\n' "$ENV_FILE"
